### ISSUE TITLE
TypeError: credit_card_type_1.default is not a function

### ISSUE THREAD

**Issue by KuldeepPanchal669** [braintree/credit-card-type#68] opened 2018-02-28 12:24 UTC
### General information

* My Angular version: 5.2.0
* My Angular Cli Version: 1.7.0-beta.3

### Issue description

I have imported the function as shown below :
import creditCardType, { getTypeInfo, types as CardType } from 'credit-card-type';

But when using this function like below:
creditCardType(ccnum).filter(function(card) {
            console.log(card);
        });

it is giving error : TypeError: credit_card_type_1.default is not a function

Please suggest me how to resolve this, it was working with angular2, after updating to angular5 it doesn't seem to work.

**Comment by crookedneighbor** [comment] 2018-02-28 22:42
Was able to reproduce. You want this instead:

```js
import * as creditCardType from 'credit-card-type';
```

to properly import it. The way you're doing it right now, `creditCardType` is undefined, since it's written as a common js module and does not have a `default` property.

I think this answers your question, so I'm closing this issue, but feel free to comment here if it doesn't.

**Closed by crookedneighbor** 2018-02-28 22:42 UTC
