### ISSUE TITLE
[Feature] CardType from Brazil: Elo

### ISSUE THREAD

**Issue by luisibanhi** [braintree/credit-card-type#65] opened 2018-01-31 12:22 UTC
### General information

* Library version: 6.0.0
* Browser and OS: Chrome 63.0.3239.132 (64-bit) on MacOS 10.13.2 

### Issue description

I'm from brazil, and here, we have a credit card type called "Elo", i want that type of card be accepted in this library ... so, i will send a pull request to this.

**Comment by crookedneighbor** [comment] 2018-01-31 12:40
Closed as a duplicate of https://github.com/braintree/credit-card-type/issues/57 and https://github.com/braintree/credit-card-type/issues/60

**Comment by crookedneighbor** [comment] 2018-01-31 12:40
See those issues for details

**Closed by crookedneighbor** 2018-01-31 12:40 UTC
